apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
spec:
  containers:
    - image: redis
      name: redis-container
      volumeMounts:
        - mountPath: /redis-master
          name: config

  volumes:
    - name: config
      configMap:
        name: redis-config
        items:
          - key: redis-config
            path: redis.conf
